import '~/styles/globals.css';
import { Source_Serif_4 } from '@next/font/google';

export const metadata = {
  title: 'Create T3 App',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

const sourceSerif = Source_Serif_4({
  weight: ['400', '500', '600', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="bg-sea-cream">
      <body className={sourceSerif.className}>{children}</body>
    </html>
  );
}
